name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Langkah ini akan membuat/memperbaiki akses file Gradle agar bisa di-build
      - name: Setup Gradle
        run: |
          if [ ! -f "gradlew" ]; then
            echo "gradlew tidak ditemukan, mencoba generate ulang..."
            gradle wrapper
          fi
          chmod +x gradlew

      # Membangun APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Mengupload hasil APK ke tab Actions
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
